[project]
name = "modal_metaflow"
version = "0.1.0"
description = "A Metaflow plugin for running Flow steps on Modal"
readme = "README.md"
authors = [
    { name = "Jason Mancuso", email = "7891333+jvmncs@users.noreply.github.com" },
]
requires-python = ">=3.11"
dependencies = ["modal", "metaflow"]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["metaflow_extensions*"]

[tool.setuptools.package-data]
metaflow_extensions = ["py.typed"]

[tool.pyright]
venvPath = "."
venv = ".venv"

[dependency-groups]
dev = [
    "invoke>=2.2.0",
    "psycopg[binary]>=3.2.10",
    "pytest>=8.4.2",
]
